# หมายเหตุ:ใน yml แต่ละระดับจะเติมด้วยช่องว่าง 2 ช่อง
ชื่อ:  Flutter 

on: 
  # เรียกใช้การดำเนินการนี้เมื่อคุณกดที่ master 
  push: 
    branches: [ "main" ] 
  # เรียกใช้การดำเนินการนี้เมื่อมีการสร้าง PR เทียบกับ master 
  pull_request: 
    branches: [ "main" ] 

jobs: 
  flutter_job: 

    # บนเครื่อง เราสามารถใช้ windows-latest หรือ ubuntu-latest ได้เช่นกัน
    # เราเลือก macos-latest เพราะเราจะสร้างสำหรับ iOS ด้วย
    รันบน:  macos-latest 

    ขั้นตอน: 

      # โคลนโครงการบนเครื่อง
      -  ใช้:  actions/checkout@v4 

      # ติดตั้ง flutter และการอ้างอิงที่เกี่ยวข้องบนเครื่องนี้
      -  ชื่อ:  การตั้งค่า Flutter 
        ใช้:  subosito/flutter-action@v2 
        พร้อมกับ: 
          channel:  'stable' 
          # flutter-version: '3.16.8' 
          # ^ หากคุณต้องการใช้ flutter เวอร์ชันเฉพาะ
      
      # ดึงการอ้างอิงของ proj จาก pub 
      -  ชื่อ:  ติดตั้ง การอ้างอิง
        เรียกใช้:  flutter  pub  get 
          # ^ หากคุณต้องการ เพื่อใช้เวอร์ชันเฉพาะของ Flutter
