# หมายเหตุ:ใน yml แต่ละระดับจะเติมด้วยช่องว่าง 2 ช่อง
ชื่อ:  Flutter 

on: 
  # เรียกใช้การดำเนินการนี้เมื่อคุณกดที่ master 
  push: 
    branches: [ "master" ] 
  # เรียกใช้การดำเนินการนี้เมื่อมีการสร้าง PR เทียบกับ master 
  pull_request: 
    branches: [ "master" ] 

jobs: 
  flutter_job: 

    # บนเครื่อง เราสามารถใช้ windows-latest หรือ ubuntu-latest ได้ด้วย
    # เราเลือก macos-latest เพราะเราจะสร้างสำหรับ iOS ด้วย
    เรียกใช้บน:  macos-latest 

    ขั้นตอน: 

      # โคลนโครงการบนเครื่อง
      -  ใช้:  actions/checkout@v4
